version: '3.8'

services:
  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile
    ports:
      - "5173:5173"
    volumes:
      - ./frontend:/app
      - /app/node_modules
    environment:
      - VITE_API_URL=http://backend:3000
    depends_on:
      - backend

  backend:
    build:
      context: ./go-backend
      dockerfile: Dockerfile
    ports:
      - "3000:3000"
    volumes:
      - ./go-backend:/app
    environment:
      - GO_ENV=development

networks:
  default:
    driver: bridge
